### ISSUE TITLE
Failed to "make"

### ISSUE THREAD

**Issue by Son-Lam** [rabbitmq/rabbitmq-web-mqtt#15]
Hello, 

Could you help to see why I cannot build from source with error:

......
make[3]: Leaving directory `/home/son-sparq/Downloads/rabbitmq-web-mqtt-rabbitmq_v3_7_0_milestone7/deps/amqp_client'
[[ -d /home/son-sparq/.mix/archives ]] || mix local.hex --force
/bin/sh: mix: command not found
make[2]: *** [deps] Error 127
make[2]: Leaving directory `/home/son-sparq/Downloads/rabbitmq-web-mqtt-rabbitmq_v3_7_0_milestone7/deps/rabbitmq_cli'
make[1]: *** [deps] Error 2
make[1]: Leaving directory `/home/son-sparq/Downloads/rabbitmq-web-mqtt-rabbitmq_v3_7_0_milestone7/deps/rabbit'
make: *** [deps] Error 2

Best Regards,

**Comment by michaelklishin** [comment]
Long story short, we are in the process of integrating new CLI tools so it's a better idea to [clone the entire umbrella repository](https://github.com/rabbitmq/rabbitmq-public-umbrella).

**Comment by michaelklishin** [comment]
and well, there are [binary builds available](https://github.com/rabbitmq/rabbitmq-web-mqtt#binary-builds).
