### ISSUE TITLE
cuttlefish schema does not translate ip address correctly

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-web-mqtt#26]
Reported here: https://stackoverflow.com/q/49396093/1466825

Using the following `rabbitmq.conf` file will crash on startup:

```
web_mqtt.tcp.ip = 127.0.0.1
web_mqtt.tcp.port = 12345
```

The ip address is translated into the string `"127.0.0.1"` but ranch expects a term of type `inet:ip_address()` as defined [here](http://erlang.org/doc/man/inet.html#type-ip_address)

I also think [the docs](https://www.rabbitmq.com/web-mqtt.html) need to be updated to reflect the actual cuttlefish schema.

**Comment by michaelklishin** [comment]
@lukebakken I'm not following about the docs. Should we simply use the proper Cuttlefish data type, `ip`, as [we do in rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server/blob/master/priv/schema/rabbit.schema#L24)?

**Comment by lukebakken** [comment]
Yep, that's exactly what I was looking for.

As for the docs, we have `web_mqtt.port = 12345` when it should be `web_mqtt.ip.port = 12345` but that will change too if we go with `rabbitmq-server`'s schema.

**Comment by michaelklishin** [comment]
I think we can fix the schema (the key name used in the docs makes more sense) or even support both fairly easily.

**Comment by konoufo** [comment]
Why do the docs [here](https://www.rabbitmq.com/web-mqtt.html) mention `web_mqtt.port` which doesn't exist as a configuration parameter ?

**Comment by lukebakken** [comment]
@konoufo apparently we missed that change on the website. If you'd like to submit a PR against the `live` branch to fix it, the relevant file is here: https://github.com/rabbitmq/rabbitmq-website/blob/live/site/web-mqtt.md

**Comment by michaelklishin** [comment]
The docs have been [updated](https://www.rabbitmq.com/web-mqtt.html?skipcache=1) to use `web_mqtt.tcp.port`. Thank you for noticing.

**Comment by konoufo** [comment]
Perfect!
