### ISSUE TITLE
Max connections

### ISSUE THREAD

**Issue by bradleyd** [rabbitmq/rabbitmq-web-mqtt#28]
Hello,
I am testing rabbitmq 3.7.4 with web-mqtt. I am running into an issue where I can only successfully connect around 1K clients.  I am testing using the golang paho client.  All tests are running from a large EC2 host.  Rabbit is running on a host with 16 cores and 32GB ram.  I can connect 4x when just hitting mqtt port.  I have my file handles set to a large number.  I upped the tcp acceptors to 100.  Is there any other setting I am missing? 

I appreciate any help you can give.

**Comment by lukebakken** [comment]
Hi Bradley -

Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

Please post your question or issue to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

In your specific case, please provide the output of the following commands as file attachments to your message:

* `sudo sysctl -a`
* `rabbitmqctl eval 'os:cmd("ulimit -a").'`

>  I am running into an issue where I can only successfully connect around 1K clients

What issue are you seeing? Stacktraces, errors? Log entries? Timeouts? Please provide more detail in your message to the mailing list.

Thanks again!
Luke

**Comment by michaelklishin** [comment]
There are also doc sections on

 * [Tuning for a large number of connections](http://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections)
 * [How to verify effective configuration](http://www.rabbitmq.com/configure.html#verify-configuration-config-file-location)
 * [How to tweak kernel resources](http://www.rabbitmq.com/install-debian.html#kernel-resource-limits) on various Debian distributions (as well as [RPM-based ones](http://www.rabbitmq.com/install-rpm.html#kernel-resource-limits))

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/d/msg/rabbitmq-users/3djFTERjf44/zjtbpC8qBAAJ).

**Comment by lukebakken** [comment]
For what it's worth, RabbitMQ has a `connection_max` setting that is passed to ranch [here](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/tcp_listener_sup.erl#L52-L59).

**Comment by michaelklishin** [comment]
@essen is it a requirement or a recommended practice for projects that use Ranch to set `connection_max`? Should this plugin configure it the same way RabbitMQ server does? If so we will file another issue.

**Comment by essen** [comment]
For Ranch `max_connections` is 1024 by default so it's necessary for the cases where you need more but RabbitMQ's `connection_max` sets the `max_connections` value and defaults to infinity.

In Cowboy it's only used to limit the number of HTTP connections. As soon as an HTTP connection becomes a Websocket connection, the connection is no longer counted and so you can have 1024 as a limit and still have 10k Websocket connections.

In general you want to limit connections that end up taking a lot of resources (like many HTTP requests do) and not the ones that stay mostly idle (like Websocket).

Therefore I do not think this plugin has to configure anything. Cowboy takes care of it. That's assuming there's no bug of course. I will add a test case to Cowboy next week to confirm that Websocket connections are not counted, as is intended.

**Comment by bradleyd** [comment]
@essen Thanks.  I am putting together a test to show where I "appear to be" hitting that 1024 limit.  

Thanks again for all the help everyone.

**Comment by saurwad** [comment]
Hello @bradleyd , did you ever manage to solve this. I feel I am running into same issue with Rabbit 3.7.13 and Erlang 21.3.  
I run into 1k limit both with web_mqtt as well as web_stomp, so its probably something to do with Ranch

**Comment by lukebakken** [comment]
@saurwad please post your question and configuration files to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) rather than discussing it here.

**Comment by bradleyd** [comment]
@saurwad i will post something on the user list on how i overcame this.

**Comment by saurwad** [comment]
Thank you Bradley
I have in Desperation. Switched to Amazonmq. But would love to go back to
Rabbi t

**Comment by bradleyd** [comment]
look here [user group](https://groups.google.com/forum/#!topic/rabbitmq-users/O8MdO95e2Hc)

**Comment by michaelklishin** [comment]
The above thread suggests setting `tcp_config.max_connections` for Web MQTT to `infinity`. Looks like Ranch limits that value [to 1024 by default](https://github.com/ninenines/ranch/blob/30604262b5934b38e9f55f0d3ef44f8aed5310de/doc/src/manual/ranch.asciidoc#L124). RabbitMQ [sets that to `infinity` for AMQP 0-9-1, AMQP 1.0 and other tcp_listener_sup users](https://github.com/rabbitmq/rabbitmq-server/blob/626033a8c415be7ffc8360eac985f97d054935b3/src/tcp_listener_sup.erl#L50), the same can be done for this and other protocol plugins.

**Comment by michaelklishin** [comment]
The `infinity` value has been used in `tcp_listener_sup` for [at least two years](https://github.com/rabbitmq/rabbitmq-server/commit/e6448b2170fcc48cc6275f917ac025e13c43ddf2) (likely as long as we've been using Ranch).

**Comment by michaelklishin** [comment]
[More evidence](https://github.com/ninenines/cowboy/issues/1279#issuecomment-378412936) that not configuring `max_connections` explicitly will have a relatively low effective cap (1024 + pending TCP connection queue/backlog).

**Comment by michaelklishin** [comment]
Opened #55 for this plugin and https://github.com/rabbitmq/rabbitmq-web-stomp/issues/113 for Web STOMP because the default here does not match that of other protocols (as suggested by @bradleyd in the original report).

**Comment by bradleyd** [comment]
@michaelklishin Thanks for opening the issues!
