### ISSUE TITLE
Add ability to disable non-TLS listeners when TLS is enabled

### ISSUE THREAD

**Issue by weeco** [rabbitmq/rabbitmq-web-mqtt#31]
I am using the MQTT plugin and I'd like to disable the listener for MQTT (websockets) without SSL:

```
    mqtt.listeners.tcp.default = 1883
    mqtt.listeners.ssl.default = 8883
    web_mqtt.tcp.port = 1889
    web_mqtt.ssl.port = 4978
```

When I use `none` instead of `1883` the bootup fails with a parse error (expected an int). How can I disable the TCP default and websocket default listeners?

**Comment by michaelklishin** [comment]
This plugin's config schema doesn't support disabling listeners like [RabbitMQ core does](https://github.com/rabbitmq/rabbitmq-server/blob/master/priv/schema/rabbit.schema#L20).

**Comment by lukebakken** [comment]
Also see:
* https://github.com/rabbitmq/rabbitmq-web-stomp/issues/100
* https://github.com/rabbitmq/rabbitmq-management/pull/618
