### ISSUE TITLE
Client Id Missing In Authentication

### ISSUE THREAD

**Issue by amalikctec** [rabbitmq/rabbitmq-web-mqtt#33]
Hi

RabbitMQ version: 3.7.8 (official docker image)

We have setup the http authentication backend on RabbitMQ to do custom authentication of MQTT devices. We will support both TCP and Websocket based transports. However we are seeing some inconsistency in how the TCP and the Websocket (web-mqtt) backends are authenticating the device.

When using TCP the following URI is used:

http://<auth_service>/rabbitmq_auth/user?username=userA&password=df3facf6057258a9346a5ae0ff3f3996&vhost=%2F&client_id=65e2332a-0dd8-4b66-b989-1dea138a21cc

The TCP backend is sending the client Id (parameter) in addition to the username, password and vhost.

However  the WebScoket backend seems to be using the following URI:
http://<auth_service>/user?username=userA&password=df3facf6057258a9346a5ae0ff3f3996&vhost=%2F

It does not seem to be sending the client Id parameter when authenticating the device.

Is it possible to send the client Id from the websocket backend as well? It will make the authentication consistent on our end.

Please let me know if we can provide anything from our end to help with this issue.

Thanks

**Comment by michaelklishin** [comment]
We plan on refactoring this plugin for 3.7.9 for unrelated reasons but will take a look.

**Comment by amalikctec** [comment]
Good to hear.

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-mqtt/issues/168 since this plugin cannot support what the MQTT one does not.
