### ISSUE TITLE
Disable TLS 1.0 on server 2012 R2

### ISSUE THREAD

**Issue by dharrison1234** [rabbitmq/rabbitmq-web-mqtt#42]
I haven't been able to find the command to disable TLS 1.0 in RabbitMQ on server 2012 R2.

**Comment by lukebakken** [comment]
Hello! Please post this question to [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users). Thanks.

**Comment by michaelklishin** [comment]
RabbitMQ TLS guide has a section that's titled [Limiting TLS Versions Used](http://www.rabbitmq.com/ssl.html#tls-versions). There is nothing Windows-specific about that.

**Comment by dharrison1234** [comment]
These TLS settings are in the config file?

**Comment by michaelklishin** [comment]
Please read the guide, it has plenty of configuration examples, mentions what [settings are essential](http://www.rabbitmq.com/ssl.html#enabling-tls), covers how TLS works and how it is used with RabbitMQ, how to evaluate security of a certain TLS setup and much more.

We put a lot of effort into the docs, please invest some time in studying them.
