### ISSUE TITLE
Register multiple TCP/SSL Listeners and provide a virtual host mapping

### ISSUE THREAD

**Issue by Guruth** [rabbitmq/rabbitmq-web-mqtt#71]
The MQTT plugin offers the possibility to register multiple TCP/SSL listeners, in addition, it is possible to define a MQTT port to virtual host mapping by providing the **mqtt_port_to_vhost_mapping** configuration value.

It would be great to have the same capability for the web-mqtt plugin.

**Comment by michaelklishin** [comment]
This is a very rarely used feature in the MQTT plugin we would rather remove. Adding it in more places will require significantly more demand from the community. At the moment, this is a `wontfix`. It is possible to provide a virtual host [as part of a username using a convention](https://www.rabbitmq.com/mqtt.html#virtual-hosts): this value is passed to the MQTT plugin as is.
